name:                constrained-control
version:             0.1.0
github:              dcastrop/constrained-control
license:             BSD3
author:              David Castro-Perez <david.castro.dcp@gmail.com>
maintainer:          David Castro-Perez <david.castro.dcp@gmail.com>
copyright:           2018 David Castro-Perez
extra-source-files:
- README.md
- ChangeLog.md
synopsis:            Redefinition of Control.Category and Control.Arrow classes
                     with arbitrary class constraints on the elements.
# category:            Web
description:         Please see the README on Github at <https://github.com/dcastrop/constrained-control#readme>
dependencies:
- base >= 4.7 && < 5
- constraints >= 0.9 && < 1.0
- singletons >= 2.4 && < 2.5
- ivector >= 0.1 && < 0.2

library:
  source-dirs: src
  ghc-options:
  - -Wall
